defaults:
  exp_label: 'exp'
  logdir: null
  traindir: null
  evaldir: null
  offline_traindir: ''
  offline_evaldir: ''
  seed: 0
  steps: 1e6
  eval_every_collection_episodes: 200
  eval_episode_num: 20
  test_episode_num: 1000
  log_every: 1e4
  log_imagined_horizon_effective_length: False
  reset_every: 0
  device: 'cuda:0'
  compile: True
  precision: 32
  debug: False
  expl_gifs: False
  video_pred_log: False

  # Environment
  task: 'dmc_walker_walk'
  size: [ 64, 64 ]
  envs: 10
  action_repeat: 1
  time_limit: 1000
  grayscale: False
  prefill: 25
  eval_noise: 0.0
  reward_EMA: True
  num_meta_episodes: 1
  max_episode_length: 100
  meta_learning: False

  # Model
  rnn_detach_every: -1
  dyn_cell: 'gru_layer_norm'
  dyn_hidden: 64
  dyn_deter: 512
  dyn_stoch: 16
  dyn_discrete: 16
  dyn_input_layers: 1
  dyn_output_layers: 1
  dyn_rec_depth: 1
  dyn_shared: False
  dyn_mean_act: 'none'
  dyn_std_act: 'sigmoid2'
  dyn_min_std: 0.1
  dyn_temp_post: True
  grad_heads: [ 'decoder', 'reward', 'cont' ]
  units: 128
  reward_layers: 2
  cont_layers: 2
  value_layers: 2
  actor_layers: 2
  act: 'SiLU'
  norm: 'LayerNorm'
  encoder:
    { mlp_keys: '$^', cnn_keys: 'image', act: 'SiLU', norm: 'LayerNorm', cnn_depth: 32, kernel_size: 4, minres: 4, mlp_layers: 2, mlp_units: 512, symlog_inputs: True }
  decoder:
    { mlp_keys: '$^', cnn_keys: 'image', act: 'SiLU', norm: 'LayerNorm', cnn_depth: 32, kernel_size: 4, minres: 4, mlp_layers: 2, mlp_units: 512, cnn_sigmoid: False, image_dist: mse, vector_dist: symlog_mse }
  value_head: 'symlog_disc'
  reward_head: 'symlog_disc'
  dyn_scale: '0.5'
  rep_scale: '0.1'
  kl_free: '1.0'
  cont_scale: 1.0
  reward_scale: 1.0
  weight_decay: 0.0
  unimix_ratio: 0.01
  action_unimix_ratio: 0.01
  initial: 'learned'
  reconstruction_window: 3

  # Training
  batch_size: 16
  batch_length: 64
  behavior_batch_length: 512
  hidden_states_subsample: 64
  sample_first: False
  train_ratio: 0.03
  mamba_context: True
  initial_wm_horizon: 50
  reach_wm_horizon_limit: -1
  pretrain: 100
  model_lr: 1e-4
  opt_eps: 1e-8
  grad_clip: 1000
  value_lr: 3e-5
  actor_lr: 3e-5
  ac_opt_eps: 1e-5
  value_grad_clip: 100
  actor_grad_clip: 100
  dataset_size: 1000000
  slow_value_target: True
  slow_target_update: 1
  slow_target_fraction: 0.02
  opt: 'adam'

  # Behavior.
  discount: 0.997
  discount_lambda: 0.95
  imag_horizon: 10
  imag_gradient: 'dynamics'
  imag_gradient_mix: '0.0'
  imag_sample: True
  actor_dist: 'normal'
  actor_entropy: '3e-4'
  actor_state_entropy: 0.0
  actor_init_std: 1.0
  actor_min_std: 0.1
  actor_max_std: 1.0
  actor_temp: 0.1
  expl_amount: 0.0
  eval_state_mean: False
  collect_dyn_sample: True
  behavior_stop_grad: True
  value_decay: 0.0
  future_entropy: False

  # Exploration
  expl_behavior: 'greedy'
  expl_until: 0
  expl_extr_scale: 0.0
  expl_intr_scale: 1.0
  disag_target: 'stoch'
  disag_log: True
  disag_models: 10
  disag_offset: 1
  disag_layers: 4
  disag_units: 400
  disag_action_cond: False
  all_layers: 0

dmc_vision:
  steps: 3e7
  reach_wm_horizon_limit: 5e6
  train_ratio: 0.03
  video_pred_log: true
  encoder: { mlp_keys: '$^', cnn_keys: 'image' }
  decoder: { mlp_keys: '$^', cnn_keys: 'image' }

dmc_proprio:
  steps: 1e6
  reach_wm_horizon_limit: 5e6
  train_ratio: 0.03
  max_episode_length: 300
  logdir: ./dmc_proprio
  detach_image_from_obs: True
  encoder: { mlp_keys: '.*', cnn_keys: '$^' }
  decoder: { mlp_keys: '.*', cnn_keys: '$^' }
  small_state_space: False

dmc_proprio_goal:
  steps: 2e7
  reach_wm_horizon_limit: 5e6
  train_ratio: 0.03
  max_episode_length: 300
  logdir: ./dmc_proprio_goal
  detach_image_from_obs: true
  encoder: { mlp_keys: '.*', cnn_keys: "image" }
  decoder: { mlp_keys: '.*', cnn_keys: "image" }
  goal_dist_theta: 1
  goal_dist_radius: 1
  dense_reward: False
  small_state_space: True
  actor_lr: 6e-05
  model_lr: 2e-4
  value_lr: 6e-05
  num_goals: 1

panda_reacher:
  steps: 2e7
  reach_wm_horizon_limit: 5e6
  train_ratio: 0.06
  envs: 1
  max_episode_length: 50
  num_meta_episodes: 3
  logdir: ./panda_reacher
  encoder: { mlp_keys: '.*', cnn_keys: "image" }
  decoder: { mlp_keys: '.*', cnn_keys: "image" }
  actor_lr: 6e-05
  model_lr: 2e-4
  value_lr: 6e-05

dmc_vision_goal:
  steps: 30e6
  reach_wm_horizon_limit: 5e6
  train_ratio: 0.06
  max_episode_length: 300
  logdir: ./dmc_vision_goal
  detach_image_from_obs: false
  encoder: { mlp_keys: '\b(reward|time_step)\b', cnn_keys: 'image' }
  decoder: { mlp_keys: '\b(reward|time_step)\b', cnn_keys: 'image' }
  goal_dist_theta: 1
  goal_dist_radius: 1
  dense_reward: False
  small_state_space: True
  actor_lr: 6e-05
  model_lr: 2e-4
  value_lr: 6e-05
  num_goals: 1

rooms:
  steps: 6e6
  reach_wm_horizon_limit: 5e6
  encoder: { mlp_keys: '.*', cnn_keys: None, mlp_layers: 4 }
  decoder: { mlp_keys: '.*', cnn_keys: None, mlp_layers: 4 }
  logdir: ./rooms
  eval_episode_num: 100
  imag_gradient: 'reinforce'
  actor_dist: 'onehot'
  train_ratio: 0.1
  imag_horizon: 2
  num_cells: 3
  num_rooms: 3

halfcircle:
  steps: 2e6
  num_meta_episodes: 3
  initial_wm_horizon: 300
  encoder: { mlp_keys: '.*', cnn_keys: None, mlp_layers: 4 }
  decoder: { mlp_keys: '.*', cnn_keys: None, mlp_layers: 4 }
  logdir: ./halfcircle
  train_ratio: 0.01
  imag_horizon: 2
  all_layers: 2
  max_episode_length: 100
  goal_radius: 2

halfcirclewind:
  steps: 2e6
  initial_wm_horizon: 300
  num_meta_episodes: 3
  encoder: { mlp_keys: '.*', cnn_keys: None, mlp_layers: 4 }
  decoder: { mlp_keys: '.*', cnn_keys: None, mlp_layers: 4 }
  logdir: ./halfcirclewind
  train_ratio: 0.2
  imag_horizon: 10
  all_layers: 2
  max_episode_length: 100
  goal_radius: 2
  wind_force: 0.3

escaperoom:
  steps: 4e6
  initial_wm_horizon: 120
  num_meta_episodes: 2
  encoder: { mlp_keys: '.*', cnn_keys: None, mlp_layers: 4 }
  decoder: { mlp_keys: '.*', cnn_keys: None, mlp_layers: 4 }
  logdir: ./escaperoom
  train_ratio: 0.2
  imag_horizon: 10
  all_layers: 2
  max_episode_length: 60
  goal_radius: 2

humanoiddir:
  steps: 30e6
  reach_wm_horizon_limit: 15e6
  max_episode_length: 200
  num_meta_episodes: 2
  logdir: ./humanoid
  encoder: { mlp_keys: '.*', cnn_keys: '$^' }
  decoder: { mlp_keys: '.*', cnn_keys: '$^' }
  actor_lr: 6e-05
  model_lr: 2e-4
  value_lr: 6e-05

debug:
  debug: True
  pretrain: 1
  prefill: 1
  batch_size: 10
  batch_length: 20
